/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CALCprocess */

#ifndef _Included_CALCprocess
#define _Included_CALCprocess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CALCprocess
 * Method:    Process
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CALCprocess_Process
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
